project:
  type: website
  output-dir: docs

website:
  title: "Jordi A. Rivera Prince"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: publications.qmd
        text: Publications
      - href: projects.qmd
        text: Projects
      - href: article_translations.qmd
        text: Traducciones en Español
  google-analytics: 'G-PS1VX1TWKC'
        
        
format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

