project:
  type: website

website:
  title: "jriveraprince"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: publications.qmd
        text: Publications

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

